name: Publish 'Percursus'
run-name: Publish 'Percursus' (${{ github.event.inputs.release-type }})

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Art des Releases'
        required: true
        default: 'release'
        type: choice
        options:
          - Release
          - Alpha
      release-tag:
        description: 'neuer Tag (manuell)'
        required: false
      build:
        description: 'Release erstellen'
        required: false
        default: true
        type: boolean
      full-changelog:
        description: 'vollständiges Changelog erstellen'
        required: false
        default: true
        type: boolean

jobs:
  call-blueprint:
    uses: wow-addon-dev/.github/.github/workflows/release_blueprint.yml@main
    with:
      release-type: ${{ inputs.release-type }}
      release-tag: ${{ inputs.release-tag }}
      build: ${{ inputs.build }}
      full-changelog: ${{ inputs.full-changelog }}
      cf-project-id: ${{ vars.CF_PROJECT_ID }}
    secrets: inherit
